name = "FilteredMatrices"
uuid = "d9af566e-5b8c-4205-a764-d8c3ac5960e2"
authors = ["Pablo San-Jose <pablo.sanjose@csic.es>", "Bruno Amorim <amorim.bac@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
